drop database if exists data_profile;
create database data_profile;
use data_profile;
create table entry (entry_id integer not null auto_increment, entry_name varchar(255), profile_id integer, primary key (entry_id));
create table entry_feature (feature_value varchar(255), feature_id integer not null, entry_id integer not null, primary key (feature_id, entry_id));
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), profile_id integer, primary key (feature_id));
create table profile (profile_id integer not null auto_increment, profile_name varchar(255), user_id integer, primary key (profile_id));
create table role (role_id integer not null auto_increment, role_name varchar(255), primary key (role_id));
create table user (user_id integer not null auto_increment, password varchar(255) not null, username varchar(255) not null, primary key (user_id));
create table user_role (user_id integer not null, role_id integer not null, primary key (user_id, role_id));
alter table role add constraint UK_iubw515ff0ugtm28p8g3myt0h unique (role_name);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table entry add constraint FKodx5fy0lfmyfikscpwkcgmlyv foreign key (profile_id) references profile (profile_id) on delete cascade on update cascade;
alter table entry_feature add constraint FKn3cunfdepssfw1jhh32ne3oh3 foreign key (feature_id) references feature (feature_id) on delete cascade on update cascade;
alter table entry_feature add constraint FKky3ro5vr4d47m7gu3wb1jg1eo foreign key (entry_id) references entry (entry_id) on delete cascade on update cascade;
alter table feature add constraint FKixgn71nlekyrduxbrxq45jyod foreign key (profile_id) references profile (profile_id) on delete cascade on update cascade;
alter table profile add constraint FKawh070wpue34wqvytjqr4hj5e foreign key (user_id) references user (user_id) on delete cascade on update cascade;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (role_id) on delete cascade on update cascade;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (user_id) on delete cascade on update cascade;
